name: TeslaCamProcessor
options:
  bundleIdPrefix: com.teslacam
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
targets:
  TeslaCamProcessor:
    type: application
    platform: macOS
    sources:
      - Sources/TeslaCamProcessor
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.teslacam.processor
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2024"
        INFOPLIST_KEY_CFBundleDisplayName: TeslaCam Processor
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_NSMainStoryboardFile: ""
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        SWIFT_VERSION: 5.9
        MACOSX_DEPLOYMENT_TARGET: 13.0
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "-"
        ENABLE_HARDENED_RUNTIME: NO
    resources:
      - AppIcon.icns
    info:
      path: Info.plist
      properties:
        CFBundleIconFile: AppIcon
        CFBundleIdentifier: com.teslacam.processor
        CFBundleName: TeslaCam Processor
        CFBundleDisplayName: TeslaCam Processor
        CFBundlePackageType: APPL
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        LSMinimumSystemVersion: 13.0
        NSMainStoryboardFile: ""
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
        LSApplicationCategoryType: public.app-category.utilities